name: Build CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .git-blame-ignore-revs
      - .gitignore
      - CONTRIBUTING.md
      - COPYING
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - .git-blame-ignore-revs
      - .gitignore
      - CONTRIBUTING.md
      - COPYING
      - README
      - README.md
      - RELNOTES
      - SECURITY.md

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: update package information
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt-get install gcc-12 libapparmor-dev libselinux1-dev expect xzdec
    - name: configure
      run: CC=gcc-12 ./configure --enable-fatal-warnings --enable-analyzer --enable-apparmor --enable-selinux --prefix=/usr
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: print version
      run: command -V firejail && firejail --version
    - name: run tests
      run: SHELL=/bin/bash make test-github
